install.packages("shiny", dependencies = TRUE)
install.packages("devtools")
devtools::install_github("daattali/shinyjs")
install.packages("dplyr", dependencies = TRUE)
install.packages("shinydashboard", dependencies = TRUE)
install.packages("flexdashboard", dependencies = TRUE)
install.packages("leaflet", dependencies = TRUE)
install.packages("dygraphs", dependencies = TRUE)
install.packages("plotly", dependencies = TRUE)
install.packages("geosphere", dependencies = TRUE)
install.packages("data.table", dependencies = TRUE)
install.packages("lubridate", dependencies = TRUE)
install.packages("DT", dependencies = TRUE)

options(device='cairo')